<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>gravmod</AssemblyName>
    <Product>My first plugin</Product>
    <GUID>lakeull.modding.gravitynmod</GUID>
    <Version>1.0.0</Version>
    <Nullable>enable</Nullable>
    <LangVersion>13.0</LangVersion>
    <RootNamespace>gravmod</RootNamespace>
    <UltrakillDir>C:/Program Files (x86)/Steam/steamapps/common/ULTRAKILL/</UltrakillDir> <!-- Ensure that this has BepInEx installed -->
    <CopyToBepInExPluginsDir>true</CopyToBepInExPluginsDir>
    
    <RestoreAdditionalProjectSources>
      https://nuget.bepinex.dev/v3/index.json;
      https://nuget.samboy.dev/v3/index.json
    </RestoreAdditionalProjectSources>
    <GenerateDependencyFile>false</GenerateDependencyFile>
    <RunPostBuildEvent>OnBuildSuccess</RunPostBuildEvent>
  </PropertyGroup>

  <Import Project="Properties/DeployToPlugins.targets" />
  
  <ItemGroup>
    <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
    <PackageReference Include="BepInEx.Core" Version="5.*" />
    <PackageReference Include="UltraModding.PluginInfoGenerator" Version="4.*" />
    <PackageReference Include="UnityEngine.Modules" Version="2022.3.28" IncludeAssets="compile" />
  </ItemGroup>
  
  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(UltrakillDir)ULTRAKILL_Data/Managed/Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Configgy">
      <HintPath>..\..\..\..\Downloads\Configgy-1.0.7 (1)\plugins\Configgy.dll</HintPath>
    </Reference>
  </ItemGroup>
  
</Project>
